#!/usr/bin/env python3
"""Generate piano-like samples for the 61-key board.

Replaces the previous placeholder recipe (sin(f) + 0.35*sin(2f), one fixed
350 ms envelope for every key) with a struck-string model:

  * a decaying harmonic series (H1..Hn), not two partials
  * inharmonicity, so harmonics stretch above integer multiples
  * unison string beating (1/2/3 strings per note, detuned a cent or two)
  * a hammer transient, the broadband click of the strike
  * a decay time that depends on pitch -- bass rings for seconds, treble dies
    in a fraction of that, which the old fixed 350 ms got exactly backwards

Output matches the existing bundle contract: 22 050 Hz, mono, 16-bit PCM,
file names spelled with `s` for sharp (fs4.wav). Deterministic (seeded), so
re-running it over the committed bundle reproduces it byte for byte -- which is
what `test/domain/audio/note_sample_quality_test.dart` exists to enforce when
the samples are regenerated by some other means.

    pip install numpy
    python3 app/tools/generate_note_samples.py            # into the bundle
    python3 app/tools/generate_note_samples.py /tmp/out   # somewhere else

Every tuning constant below is a musical decision, not an arbitrary one: see
the comments on `sample_duration`, the unison detune, and the inharmonicity
coefficient. Changing them changes how the app sounds, and the quality test
will say so.
"""
import math
import os
import struct
import sys

import numpy as np

SR = 22050
_HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    _HERE, os.pardir, "assets", "audio", "notes"
)
A4 = 440.0

LETTER = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def note_to_midi(name: str) -> int:
    i = 1
    while i < len(name) and name[i] == "#":
        i += 1
    return LETTER[name[0]] + (i - 1) + 12 * (int(name[i:]) + 1)


def midi_to_freq(midi: int) -> float:
    return A4 * 2 ** ((midi - 69) / 12)


NATURAL = {0: "C", 2: "D", 4: "E", 5: "F", 7: "G", 9: "A", 11: "B"}
SHARP = {1: "C#", 3: "D#", 6: "F#", 8: "G#", 10: "A#"}


def sixty_one_notes():
    """C2..C7 inclusive = 61 keys, matching KeyboardLayout.sixtyOne."""
    out = []
    for midi in range(36, 97):
        pc = midi % 12
        octv = midi // 12 - 1
        out.append(f"{NATURAL[pc] if pc in NATURAL else SHARP[pc]}{octv}")
    return out


# Perceptual floor used to size each file: a note is "still ringing" until it
# falls to this fraction of its own peak. -6.91/ln(FLOOR) converts a t60 (time
# to drop 60 dB) into the time to drop to FLOOR: for 0.02 that factor is 0.565.
AUDIBLE_FLOOR = 0.02
_TO_FLOOR = math.log(1.0 / AUDIBLE_FLOOR) / 6.91


def sustain_t60(midi: int) -> float:
    """The fundamental's decay time constant.

    This is a *sustained* piano (foot on the damper pedal), not a dry staccato
    one. The reason matters: the demo engine is monophonic and strikes a note
    exactly once, so a note with an authored duration of 2 or 4 can only fill
    its slot if the sample itself keeps ringing that long. The first version of
    this file decayed like an unpedalled piano — a C5 audible for ~0.5 s — so a
    3 s held note in Amazing Grace went silent for two thirds of its own length,
    and that dead air read as a pause between notes.

    The curve is monotonic and pitched, not derived from the song list: bass
    rings for several seconds, treble for about a second, and the clip bounds
    keep every file a sane length regardless of which note a tune happens to
    hold. Mid-register (C4–C5) is where the library actually holds notes for
    three seconds, and that is exactly where a real piano sustains longest.
    """
    return float(np.clip(7.6 * 2 ** (-(midi - 60) / 15.0), 1.0, 6.2))


def sample_duration(midi: int) -> float:
    """Seconds of audio to write: until the fundamental fades to the audible
    floor, plus a short release so the file ends in silence rather than a click.
    """
    return sustain_t60(midi) * _TO_FLOOR + 0.14


def synthesize(name: str) -> np.ndarray:
    midi = note_to_midi(name)
    f0 = midi_to_freq(midi)
    t60 = sustain_t60(midi)
    n = int(SR * sample_duration(midi))
    t = np.arange(n) / SR

    # Unison strings: a real piano uses 1 (bass), 2 (mid) or 3 (treble). Slight
    # detuning between them produces the slow beat that reads as "piano" rather
    # than "organ" -- the single biggest tell in the old samples.
    if midi < 45:
        nstrings, spread = 1, 0.0
    elif midi < 57:
        nstrings, spread = 2, 1.2
    else:
        nstrings, spread = 3, 1.6
    detunes = (
        [0.0]
        if nstrings == 1
        else list(np.linspace(-spread, spread, nstrings) / 100.0)
    )

    # Inharmonicity: string stiffness pushes harmonics sharp. Larger for the
    # short, thick bass strings.
    B = 0.0008 * 2 ** (-(midi - 48) / 24.0)

    nyquist = SR / 2
    max_h = int(min(26, (nyquist * 0.92) / f0))
    if max_h < 1:
        max_h = 1

    signal = np.zeros(n)
    for h in range(1, max_h + 1):
        fh = f0 * h * math.sqrt(1 + B * h * h)
        if fh >= nyquist * 0.98:
            break
        # Amplitude rolls off with harmonic number; the exponent is a touch
        # steeper in the treble, where real strings lose upper partials.
        p = 1.12 + 0.004 * max(0, midi - 60)
        amp = (1.0 / h) ** p
        # Higher harmonics decay faster -- the brightness of the strike fades
        # well before the fundamental does. The 0.5 factor is what makes the
        # note darken as it sustains, and the quality test measures it.
        partial_t60 = t60 / (1.0 + 0.5 * (h - 1))
        env = np.exp(-t * (6.91 / partial_t60))
        partial = np.zeros(n)
        for cents in detunes:
            ratio = 2 ** (cents / 12.0)
            partial += np.sin(2 * math.pi * fh * ratio * t)
        signal += amp * env * partial / len(detunes)

    # Hammer transient: a short broadband burst at the strike. Without it every
    # note begins with a smooth sine-like swell, which no struck string does.
    rng = np.random.default_rng(1234 + midi)
    noise = rng.standard_normal(n)
    strike_len = int(SR * 0.006)
    if strike_len > 0:
        burst = np.exp(-np.arange(strike_len) / (strike_len / 4.0))
        noise[:strike_len] *= burst * 3.0
        noise[strike_len:] = 0.0
    signal += 0.055 * noise

    # Attack ramp: strings do not start at full amplitude.
    attack = int(SR * 0.004)
    if attack > 0 and n > attack:
        signal[:attack] *= np.linspace(0.0, 1.0, attack) ** 1.5

    # Release fade so the file ends at zero instead of clicking.
    rel = min(int(SR * 0.035), n // 4)
    if rel > 0:
        signal[-rel:] *= np.linspace(1.0, 0.0, rel)

    peak = np.max(np.abs(signal))
    if peak > 0:
        signal = signal / peak * 0.89  # headroom, no clipping
    return signal


def write_wav(path: str, data: np.ndarray):
    clipped = np.clip(data, -1.0, 1.0)
    pcm = (clipped * 32767.0).astype("<i2")
    with open(path, "wb") as f:
        n = len(pcm)
        f.write(b"RIFF")
        f.write(struct.pack("<I", 36 + n * 2))
        f.write(b"WAVEfmt ")
        f.write(struct.pack("<IHHIIHH", 16, 1, 1, SR, SR * 2, 2, 16))
        f.write(b"data")
        f.write(struct.pack("<I", n * 2))
        f.write(pcm.tobytes())


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    notes = sixty_one_notes()
    assert len(notes) == 61, len(notes)
    total = 0
    for name in notes:
        base = name.lower().replace("#", "s")
        path = os.path.join(OUT_DIR, f"{base}.wav")
        write_wav(path, synthesize(name))
        total += os.path.getsize(path)
    print(f"wrote {len(notes)} files to {OUT_DIR} ({total/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
